# Generated by Django 5.1.6 on 2025-03-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_mail', models.EmailField(max_length=100)),
                ('contact_subject', models.CharField(max_length=100)),
                ('contact_message', models.TextField()),
            ],
        ),
    ]
