# Generated by Django 5.2.2 on 2025-06-21 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='updateAt',
            new_name='updatedAt',
        ),
    ]
