# Generated by Django 5.2.2 on 2025-06-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_rename_updateat_todolist_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='updatedAt',
            field=models.DateField(null=True),
        ),
    ]
