# Generated by Django 5.1.7 on 2025-04-02 01:46

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=100)),
                ('article_date', models.DateTimeField()),
                ('article_description', models.CharField(max_length=100)),
                ('article_content', django_ckeditor_5.fields.CKEditor5Field()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=80)),
                ('contact_email', models.EmailField(max_length=80)),
                ('contact_suject', models.CharField(max_length=100)),
                ('contact_message', models.TextField(max_length=5000)),
            ],
        ),
    ]
